[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black   = "0x000000"
blue    = "0x3465a4"
cyan    = "0x06989a"
green   = "0x4e9a06"
magenta = "0x75507b"
red     = "0xcc0000"
white   = "0xd3d7cf"
yellow  = "0xc4a000"

[colors.bright]
black   = "0x555753"
blue    = "0x729fcf"
cyan    = "0x34e2e2"
green   = "0x8ae234"
magenta = "0xad7fa8"
red     = "0xef2929"
white   = "0xeeeeec"
yellow  = "0xfce94f"

[colors.primary]
background = "0x000000"
foreground = "0xbebebe"

[env]
TERM = "xterm-256color"
#WINIT_X11_SCALE_FACTOR = "randr"
WINIT_X11_SCALE_FACTOR = "1"
XCURSOR_SIZE="20"
dynamic_title = "true"

[font]
#antialias = false
size = 10

[font.normal]
family = "Misc Fixed"
style = "SemiCondensed"

[font.bold]
family = "Misc Fixed"
style = "Bold SemiCondensed"

#[font.glyph_offset]
#x = 0
#y = 0
#[font.offset]
#x = 0
#y = 0

[keyboard]
bindings = [
#{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
#{ key = "L", mods = "Control|Shift", chars = "l" },

 { key = "Plus",  mods = "Control|Shift", action  = "IncreaseFontSize" },
 { key = "Key0",  mods = "Control|Shift", action  = "ResetFontSize" },
 #{ key = "Space", mods = "Shift|Control", mode    = "~Search",           action = "None" },
 { key = "é",     mods = "Alt",           chars   = "\u001bé" },
 { key = "è",     mods = "Alt",           chars   = "\u001bè" },
 { key = "ç",     mods = "Alt",           chars   = "\u001bç" },
 { key = "à",     mods = "Alt",           chars   = "\u001bà" },
 { key = "-",     mods = "Alt",           chars   = "\u001b6" }
]

[selection]
semantic_escape_chars = ",;│`|:\"' ()[]{}<>\t*/=-.%@"
#save_to_clipboard = true


