#!/usr/bin/env bash
case "$1" in
    LOCK)
        ;;
    UNBLANK)
        (
            if [ "$XDG_SESSION_TYPE" = x11 ]; then
                source ~/dotfiles/bin/mouse.sh
                main
            fi
        )
        ;;
esac
