#!/usr/bin/env bash
temp=/tmp/$(whoami)/mute-state
case "$1" in
    LOCK)
        pacmd dump | grep -E '^(set-sink-mute|set-source-mute)' > "$temp"
        pacmd dump | grep -E '^(set-sink-mute|set-source-mute)' | while read cmd sink state _; do
            if [ "$state" = no ]; then
                echo "muting '$sink'"
                pacmd "$cmd" "$sink" yes
            fi
        done
        ;;
    UNBLANK)
        pacmd < "$temp"
        ;;
esac
