#theme = "solarized-dark"
#theme = "solarized-light"
#theme = "slick"

icons = "awesome"
#icons = "awesome5"
#icons = "material"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
format = "{player}"

[[block]]
block = "networkmanager"
#on_click = "alacritty -e nmtui"
on_click = "networkmanager_dmenu"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "net"
device = "wlp3s0"
#format = "{ssid} {signal_strength} {ip} {speed_down}" # {graph_down}"
format = "{speed_down} {speed_up}" # {graph_down}"
interval = 5
use_bits = false


#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "cpu"
interval = 3
#format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

#[[block]]
#block = "backlight"
##device = "intel_backlight"
#device = "ddcci9"

[[block]]
block = "backlight"
#device = "intel_backlight"
device = "amdgpu_bl0"

[[block]]
block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
format = "{weather} {temp}°"
service = { name = "openweathermap", api_key = "f7b59a94803950edace9453ba2a7b825", city_id = "2995469", units = "metric" }

[[block]]
block = "sound"
#driver = "pulseaudio"
show_volume_when_muted = true
on_click = "pavucontrol"

[[block]]
block = "custom"
command = '~/dotfiles/bin/governor'
json = true
on_click = "~/dotfiles/bin/governor-toggle"
interval = 10

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m/%Y %R"
locale = "fr_FR"
timezone = "Europe/Paris"

