#theme = "solarized-dark"
#theme = "solarized-light"
#theme = "slick"
#theme = "native"
#theme = "space-villain"

#icons = "awesome"
#icons = "awesome5"
#icons = "material"

[theme]
#theme = "native"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
headphones = ""

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "music"
#player = "spotify"
#buttons = ["play", "next"]
#format = "$player"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[block.theme_overrides]
idle_bg = "#123412"
info_bg = "#125012"

#[[block]]
#block = "networkmanager"
##on_click = "alacritty -e nmtui"
#on_click = "networkmanager_dmenu"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = []

#[[block]]
#block = "net"
#device = "fabulous-wg4"
#format = "$icon $device:$ip"
#interval = 5
#[block.theme_overrides]
#idle_bg = "#341234"

[[block]]
block = "net"
device = "tailscale0"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"
#info_bg = "#125012"

[[block]]
block = "net"
device = "wlan0"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"
#info_bg = "#125012"

[[block]]
block = "net"
device = "eno1"
#format = "$ip $speed_down.eng(prefix:M) $speed_up.eng(prefix:M)" # $graph_down"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"
#info_bg = "#125012"

[[block]]
block = "memory"
#display_type = "memory"
#format_mem = "$mem_used/$mem_total"
#format_swap = "$swap_used_percents"
format = "$icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)"

#[[block]]
#block = "custom"
#command = '~/dotfiles/bin/governor'
#json = true
#interval = 10
#[[block.click]]
#button = "left"
#cmd = "~/dotfiles/bin/governor-toggle"

[[block]]
block = "custom"
command = "~/dotfiles/bin/bluetooth-profile"
interval = "once"
#hide_when_empty = true
[[block.click]]
button = "left"
update = true
[[block.click]]
button = "right"
cmd = "~/dotfiles/bin/bluetooth-profile toggle; killall -SIGUSR1 i3status-rs"
[block.theme_overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

#[[block]]
#block = "bluetooth"
#mac = "30:50:75:38:6D:EF"
#format = "75t"
#[block.theme_overrides]
#idle_bg = "#123456"
##idle_fg = "#abcdef"

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true
format = "$output_name $volume"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.mappings]
"alsa_output.pci-0000_0b_00.3.iec958-stereo" = ""
"bluez_output.30_50_75_38_6D_EF.1" = " "
"alsa_output.usb-Samsung_USBC_Headset_20190816-00.analog-stereo" = ""
"alsa_output.usb-0b0e_Jabra_SPEAK_510_USB_50C2ED2B37C8022000-00.analog-stereo" = "  Jabra"
"alsa_output.usb-0b0e_Jabra_SPEAK_510_USB_50C2ED2B37C8022000-00.3.analog-stereo" = "  Jabra"

[block.theme_overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%R', l:'fr_FR') Portland"
timezone = "America/Los_Angeles"
[block.theme_overrides]
idle_bg = "#341212"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%R', l:'fr_FR') India"
timezone = "Asia/Calcutta"
[block.theme_overrides]
idle_bg = "#341212"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%R', l:'fr_FR') HK"
timezone = "Asia/Hong_Kong"
[block.theme_overrides]
idle_bg = "#341212"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%a %d/%m/%Y %R', l:'fr_FR')"
timezone = "Europe/Paris"
[block.theme_overrides]
idle_fg = "#D0D0D0"
idle_bg = "#123412"

