#theme = "solarized-dark"
#theme = "solarized-light"
#theme = "slick"
#theme = "native"
#theme = "space-villain"

#icons = "awesome"
#icons = "awesome5"
#icons = "material"

[theme]
#theme = "native"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
headphones = ""

[[block]]
block = "music"
#player = "spotify"
#buttons = ["play", "next"]
#format = "$player"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "net"
device = "enp2s0f0"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"
#info_bg = "#125012"

[[block]]
block = "net"
device = "wlp3s0"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"
#info_bg = "#125012"

[[block]]
block = "net"
device = "tailscale0"
format = "$icon $device:$ip"
interval = 5
[block.theme_overrides]
idle_bg = "#341234"


[[block]]
block = "memory"
#display_type = "memory"
#format_mem = "$mem_used/$mem_total"
#format_swap = "$swap_used_percents"
format = "$icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)"

[[block]]
block = "backlight"
#device = "intel_backlight"
device = "amdgpu_bl0"

#[[block]]
#block = "weather"
##format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#format = "{weather} {temp}"
#service = { name = "openweathermap", api_key = "f7b59a94803950edace9453ba2a7b825", city_id = "3028868", units = "metric" }

[[block]]
block = "custom"
command = '~/dotfiles/bin/governor'
json = true
on_click = "~/dotfiles/bin/governor-toggle"
interval = 10

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}"

[[block]]
block = "custom"
command = "~/dotfiles/bin/bluetooth-profile"
interval = "once"
#hide_when_empty = true
[[block.click]]
button = "left"
update = true
[[block.click]]
button = "right"
cmd = "~/dotfiles/bin/bluetooth-profile toggle; killall -SIGUSR1 i3status-rs"
[block.theme_overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

[[block]]
block = "bluetooth"
mac = "30:50:75:38:6D:EF"
format = "75t"
[block.theme_overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true
on_click = "pavucontrol"
format = "{output_name} {volume}"
[block.mappings]
"alsa_output.pci-0000_08_00.6.HiFi__hw_Generic_1__sink" = ""
"alsa_output.pci-0000_0b_00.3.iec958-stereo" = ""
"bluez_output.30_50_75_38_6D_EF.a2dp-sink" = ""
"bluez_output.30_50_75_38_6D_EF.headset-head-unit" = " ︁"
"alsa_output.usb-Samsung_USBC_Headset_20190816-00.analog-stereo" = ""
"alsa_output.usb-0b0e_Jabra_SPEAK_510_USB_50C2ED2B37C8022000-00.analog-stereo" = " Jabra"
[block.theme_overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%a %d/%m/%Y %R', l:'fr_FR')"
timezone = "Europe/Paris"
[block.theme_overrides]
idle_fg = "#D0D0D0"
idle_bg = "#123412"

