#!/usr/bin/env python3
import os
import subprocess

lines = os.getenv('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS', '').split('\n')
escaped = map(lambda e: f"'{e}'" if ' ' in e else e , lines)

s = ' '.join(escaped).encode()
subprocess.run(['/usr/bin/xclip'], input=s)
subprocess.run(['/usr/bin/xclip', '-selection', 'clipboard'], input=s)
