#!/usr/bin/env python3
import os
import subprocess

HOME = os.getenv("HOME")

lines = os.getenv('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS', '').strip('\n').split('\n')
print(f"lines={lines}")

# make order-document.pdf first in lines
lines.sort(key=lambda x: (not x.lower().endswith('order-document.pdf'), x))

subprocess.run(['/usr/bin/pdfunite'] + lines + ['out.pdf'])
